---
title: "Exploratory Data Analysis"
author: "Paul Hendricks"
date: "`r Sys.Date()`"
output:
  md_document:
    variant: markdown_github
---

# Exploratory Data Analysis

```{r label="settings", echo=FALSE, results='hide'}
library(knitr)
knitr::opts_chunk$set(collapse = TRUE, comment = "#>", 
                      fig.path = "imgs/eda-", 
                      echo = FALSE, message = FALSE, 
                      warning = FALSE, error = FALSE)
knitr::opts_chunk$set(fig.width = 8, fig.height = 8)
options(scipen = 999)
```

```{r label="load-libraries", results='hide'}
library(dplyr)
library(ggplot2)
library(scales)
```

```{r label="load-data"}
intervals <- read.csv("../data/prepped/intervals.csv", stringsAsFactors = FALSE)
```

```{r label="clean-data"}
intervals <- mutate(intervals, parkinsons = factor(1 * (as.character(trial) == "pd")))
```

## Visualization

```{r}
ggplot(intervals, aes(x = stride_interval)) + 
  geom_histogram() + 
  facet_wrap(~trial)

intervals %>% 
  group_by(trial) %>% 
  summarise(mean(stride_interval), 
            sd(stride_interval))


ggplot(intervals, aes(x = age, y = stride_interval)) + 
  geom_point() + 
  geom_smooth(method = 'lm')

# todo check acf to ensure that stride_interval's aren't autocorrelated
```


## Modeling

```{r}
model <- glm(parkinsons ~ stride_interval, family = binomial(link = 'logit'), data = intervals)
summary(model)
```

```{r}
train <- filter(intervals, !(participant %in% c(5)))
test <- filter(intervals, (participant %in% c(5)))

library(randomForest)
model <- randomForest(parkinsons ~ stride_interval, data = train)
results <- predict(model, newdata = test)
test[, "prediction"] <- as.numeric(as.character(results))
test[, "actual"] <- as.numeric(as.character(test[, "parkinsons"]))
library(scorer)

acc <- scorer::accuracy_score(y_true = test$actual, y_pred = test$prediction)
print(paste0("Accuracy out-of-sample: ", round(100 * acc, 2), "%"))
```


### Session Info

```{r}
sessionInfo()
```
